[package]
name = "scooch"
description = "Of Test Container Handles"
tooch
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.11.0"
tokio = { version = "1", features = ["test-util", "macros"] }
futures-util = "0.3.15"
